import { entero16, porcentaje, simple } from './TiposPid';
import type { DefinicionPidMode01 } from './TiposPid';

// Las formulas reciben bytes ya validados. No conocen Bluetooth ni React.
export const MEDICIONES_MODE_01: readonly DefinicionPidMode01[] = [
  simple(
    0x04,
    'Carga calculada del motor',
    'Motor y movimiento',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x05,
    'Temperatura del refrigerante',
    'Temperaturas',
    1,
    '°C',
    datos => datos[0] - 40,
  ),
  simple(
    0x0a,
    'Presión de combustible',
    'Combustible y emisiones',
    1,
    'kPa',
    datos => datos[0] * 3,
  ),
  simple(
    0x0b,
    'Presión del múltiple de admisión',
    'Motor y movimiento',
    1,
    'kPa',
    (datos, contexto) =>
      datos[0] * (contexto.escalas?.[3] ? (contexto.escalas[3] * 10) / 255 : 1),
  ),
  simple(
    0x0c,
    'RPM del motor',
    'Motor y movimiento',
    2,
    'rpm',
    datos => entero16(datos) / 4,
  ),
  simple(
    0x0d,
    'Velocidad del vehículo',
    'Motor y movimiento',
    1,
    'km/h',
    datos => datos[0],
  ),
  simple(
    0x0e,
    'Avance de encendido',
    'Motor y movimiento',
    1,
    '°',
    datos => datos[0] / 2 - 64,
  ),
  simple(
    0x0f,
    'Temperatura del aire de admisión',
    'Temperaturas',
    1,
    '°C',
    datos => datos[0] - 40,
  ),
  simple(
    0x10,
    'Caudal de aire MAF',
    'Motor y movimiento',
    2,
    'g/s',
    (datos, contexto) =>
      entero16(datos) *
      (contexto.escalaMaf ? (contexto.escalaMaf * 10) / 65535 : 0.01),
  ),
  simple(0x11, 'Posición de la mariposa', 'Motor y movimiento', 1, '%', datos =>
    porcentaje(datos[0]),
  ),
  simple(
    0x1f,
    'Tiempo desde el arranque',
    'Motor y movimiento',
    2,
    's',
    datos => entero16(datos),
  ),
  simple(
    0x21,
    'Distancia recorrida con MIL encendida',
    'Estados y configuracion',
    2,
    'km',
    datos => entero16(datos),
  ),
  simple(
    0x22,
    'Presión del riel relativa al vacío',
    'Combustible y emisiones',
    2,
    'kPa',
    datos => entero16(datos) * 0.079,
  ),
  simple(
    0x23,
    'Presión manométrica del riel (inyección directa)',
    'Combustible y emisiones',
    2,
    'kPa',
    datos => entero16(datos) * 10,
  ),
  simple(0x2c, 'EGR solicitada', 'Combustible y emisiones', 1, '%', datos =>
    porcentaje(datos[0]),
  ),
  simple(
    0x2d,
    'Error de EGR',
    'Combustible y emisiones',
    1,
    '%',
    datos => ((datos[0] - 128) * 100) / 128,
  ),
  simple(
    0x2e,
    'Purga evaporativa comandada',
    'Combustible y emisiones',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x2f,
    'Nivel del tanque de combustible',
    'Combustible y emisiones',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x30,
    'Ciclos de calentamiento desde borrado de DTC',
    'Estados y configuracion',
    1,
    'ciclos',
    datos => datos[0],
  ),
  simple(
    0x31,
    'Distancia desde borrado de DTC',
    'Estados y configuracion',
    2,
    'km',
    datos => entero16(datos),
  ),
  // PID 32 usa complemento a dos; PID 54 usa desplazamiento de 32767.
  simple(
    0x32,
    'Presión de vapor EVAP',
    'Combustible y emisiones',
    2,
    'Pa',
    datos =>
      (entero16(datos) >= 32768 ? entero16(datos) - 65536 : entero16(datos)) /
      4,
  ),
  simple(
    0x33,
    'Presión barométrica',
    'Motor y movimiento',
    1,
    'kPa',
    datos => datos[0],
  ),
  ...[
    'banco 1 sensor 1',
    'banco 2 sensor 1',
    'banco 1 sensor 2',
    'banco 2 sensor 2',
  ].map((sensor, indice) =>
    simple(
      0x3c + indice,
      `Temperatura del catalizador ${sensor}`,
      'Temperaturas',
      2,
      '°C',
      datos => entero16(datos) / 10 - 40,
    ),
  ),
  simple(
    0x42,
    'Voltaje del módulo de control',
    'Motor y movimiento',
    2,
    'V',
    datos => entero16(datos) / 1000,
  ),
  simple(
    0x43,
    'Carga absoluta',
    'Motor y movimiento',
    2,
    '%',
    datos => (entero16(datos) * 100) / 255,
  ),
  simple(
    0x44,
    'Relación de equivalencia solicitada (lambda)',
    'Oxigeno y mezcla',
    2,
    'lambda',
    (datos, contexto) =>
      entero16(datos) *
      (contexto.escalas?.[0] ? contexto.escalas[0] / 65535 : 1 / 32768),
  ),
  simple(
    0x45,
    'Posición relativa de la mariposa',
    'Motor y movimiento',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x46,
    'Temperatura ambiente',
    'Temperaturas',
    1,
    '°C',
    datos => datos[0] - 40,
  ),
  ...['B', 'C'].map((canal, indice) =>
    simple(
      0x47 + indice,
      `Posición absoluta de la mariposa ${canal}`,
      'Motor y movimiento',
      1,
      '%',
      datos => porcentaje(datos[0]),
    ),
  ),
  ...['D', 'E', 'F'].map((canal, indice) =>
    simple(
      0x49 + indice,
      `Posición del pedal ${canal}`,
      'Motor y movimiento',
      1,
      '%',
      datos => porcentaje(datos[0]),
    ),
  ),
  simple(
    0x4c,
    'Actuador de la mariposa solicitado',
    'Motor y movimiento',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x4d,
    'Tiempo de funcionamiento con MIL encendida',
    'Estados y configuracion',
    2,
    'min',
    datos => entero16(datos),
  ),
  simple(
    0x4e,
    'Tiempo desde borrado de DTC',
    'Estados y configuracion',
    2,
    'min',
    datos => entero16(datos),
  ),
  simple(
    0x52,
    'Porcentaje de etanol',
    'Combustible y emisiones',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x53,
    'Presión absoluta de vapor EVAP',
    'Combustible y emisiones',
    2,
    'kPa',
    datos => entero16(datos) / 200,
  ),
  simple(
    0x54,
    'Presión de vapor EVAP de rango ampliado',
    'Combustible y emisiones',
    2,
    'Pa',
    datos => entero16(datos) - 32767,
  ),
  simple(
    0x59,
    'Presión absoluta del riel',
    'Combustible y emisiones',
    2,
    'kPa',
    datos => entero16(datos) * 10,
  ),
  simple(
    0x5a,
    'Posición relativa del pedal',
    'Motor y movimiento',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x5b,
    'Carga restante de batería híbrida/EV (SOC)',
    'Motor y movimiento',
    1,
    '%',
    datos => porcentaje(datos[0]),
  ),
  simple(
    0x5c,
    'Temperatura del aceite',
    'Temperaturas',
    1,
    '°C',
    datos => datos[0] - 40,
  ),
  simple(
    0x5d,
    'Avance de la inyección',
    'Combustible y emisiones',
    2,
    '°',
    datos => entero16(datos) / 128 - 210,
  ),
  simple(
    0x5e,
    'Caudal de combustible',
    'Combustible y emisiones',
    2,
    'L/h',
    datos => entero16(datos) / 20,
  ),
];
